### ISSUE TITLE
It's my favorite style, but how make it support php files?

### ISSUE THREAD

**Issue by bravelincy** [umayr/dark-peacock#8]
I'm a F2E, and there are many files mixed with php and html syntax in my project, can you make it perfect?

**Comment by umayr** [comment]
I'll make sure it supports PHP in the next release. Stay tuned.

**Comment by bravelincy** [comment]
Thank you very much, it's also default style in current version with php files.

**Comment by umayr** [comment]
@joenil Hey man.

I have fixed this. But I need to test it. Can you provide a sample of code that was breaking this theme for you?

**Comment by bravelincy** [comment]
oh.. I use VS Code with`One Dark Pro` now...
